training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  lr_scheduler_type: constant
  learning_rate: 2.e-4
  max_steps: 100
  evaluation_strategy: steps
  eval_accumulation_steps: 1
  eval_steps: 10
  save_steps: 10
  logging_steps: 5
  optim: paged_adamw_32bit
  max_grad_norm: 0.3
  fp16: True
  warmup_ratio: 0.03
  seed: 101
  report_to: comet_ml
  load_best_model_at_end: True
model:
  id: mistralai/Mistral-7B-v0.1
  template: mistral
  max_seq_length: 1024