peft_model:
  id: fahmiaziz/mistral-finance:1.0.1
model:
  id: mistralai/Mistral-7B-v0.1
  template_name: mistral
  max_new_tokens: 512
  temperature: 1.0
setup:
  device: cuda:0
  debug: False
dataset:
  file: "testing_data.json"