training:
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 4
  max_steps: 100
  eval_steps: 10
  evaluation_strategy: steps
  warmup_ratio: 0.1
  learning_rate: 5e-6
  fp16: True
  logging_steps: 1
  optim: adamw_8bit
  weight_decay: 0.0
  lr_scheduler_type: linear
  seed: 101
  report_to: comet_ml
model:
  id: fahmi/mistral-7b-finance
  template: mistral
  max_seq_length: 1024
  max_prompt_length: 512s